<a href="https://colab.research.google.com/github/anusreeanilanu/datascience/blob/main/firstpgm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_list=([1,2,3],[4,5,6])
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(my_list)

([1, 2, 3], [4, 5, 6])


In [ ]:
n=np.zeros((4,4))
n=n.astype(int)
print(n)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [ ]:
n=np.ones((5))
n=n.astype(int)
print(n)

[1 1 1 1 1]


In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.random.rand(10)

array([0.96304602, 0.1700143 , 0.72863968, 0.07259682, 0.38593368,
       0.40271234, 0.61465265, 0.47184989, 0.95963567, 0.02404559])

In [ ]:
np.random.randn(10)

array([-0.77367278, -1.59508499,  1.24691392, -0.27974425,  1.69323878,
        0.49757292, -0.25695416,  0.11122989,  0.09922387, -0.53367874])

In [ ]:
np.random.randint(1,100)

91

In [ ]:
np.random.randint(1,100,10)

array([94, 91, 83, 81, 10, 70, 11, 14, 35, 65])

In [ ]:
arr=np.random.randint(1,100,10)
print(arr)
arr.shape

[23 99 99 56 28 77 40 80 18 97]


(10,)

In [ ]:
arr.reshape(5,2)

array([[23, 99],
       [99, 56],
       [28, 77],
       [40, 80],
       [18, 97]])

In [ ]:
arr.max()

99

In [ ]:
arr.argmax()

1

In [ ]:
arr.min()

18

In [ ]:
arr.argmin()

8

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr2[1,1]

5

In [ ]:
arr2[1:1]

array([], shape=(0, 3), dtype=int64)

In [ ]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[1:3,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
barr=arr>8
arr[barr]

array([23, 99, 99, 56, 28, 77, 40, 80, 18, 97])