In [34]:
import numpy as np

In [69]:
rows=int(input("Give the number of rows:"))

Give the number of rows:2


In [70]:
cols=int(input("Give the number of cols:"))

Give the number of cols:2


In [71]:
a = [[int(input()) for c in range (cols)] for r in range(rows)]

1
2
3
4


In [72]:
b = [[int(input()) for c in range (cols)] for r in range(rows)]

5
6
8
9


In [73]:
print("Matrix 'a' is:",a)
print("Matrix 'b' is:",b)

Matrix 'a' is: [[1, 2], [3, 4]]
Matrix 'b' is: [[5, 6], [8, 9]]


In [74]:
print("\ndot product of two matrix objects")
print(np.dot(a, b))


dot product of two matrix objects
[[21 24]
 [47 54]]


In [75]:
print("\n The transpose of a matrix 'a' is:")
print(np.transpose(a))


 The transpose of a matrix 'a' is:
[[1 3]
 [2 4]]


In [76]:
print("\n The transpose of a matrix 'b' is:")
print(np.transpose(b))


 The transpose of a matrix 'b' is:
[[5 8]
 [6 9]]


In [82]:
print("The trace of a matrix 'a' is:",np.trace(a))

The trace of a matrix 'a' is: 5


In [83]:
print("The trace of a matrix 'b' is:",np.trace(b))

The trace of a matrix 'b' is: 14


In [84]:
rank = np.linalg.matrix_rank(a)
print("Rank of the given Matrix 'a'is : ",rank)

Rank of the given Matrix 'a'is :  2


In [85]:
rank = np.linalg.matrix_rank(b)
print("Rank of the given Matrix 'b'is : ",rank)

Rank of the given Matrix 'b'is :  2


In [86]:
d= np.linalg.det(a)
print("\nDeterminant of  matrix 'a' is :")
print(int(d))


Determinant of  matrix 'a' is :
-2
